name: flutter_wills_gen
description: A Reactive Library For Flutter
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flutter_wills:
     path: ../flutter_wills

dev_dependencies:
  source_gen: ^0.7.0
  

